// Generates supabase/seed.sql from lib/mock/seed.ts.
//   node scripts/gen-seed.mjs            (reads DEMO_PASSWORD from .env.local)
// Readable seed ids ("user-carter", "job-neighbor-backend") become stable UUIDs, and
// timestamps are written relative to now() so a fresh seed always looks current.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import * as seed from "../lib/mock/seed.ts";

const root = new URL("..", import.meta.url);

function envFromFile() {
  try {
    const text = readFileSync(new URL(".env.local", root), "utf8");
    return Object.fromEntries(
      text.split("\n").filter((l) => /^[A-Z_]+=/.test(l)).map((l) => [l.slice(0, l.indexOf("=")), l.slice(l.indexOf("=") + 1)]),
    );
  } catch {
    return {};
  }
}
const DEMO_PASSWORD = process.env.DEMO_PASSWORD ?? envFromFile().DEMO_PASSWORD;
if (!DEMO_PASSWORD) throw new Error("Set DEMO_PASSWORD in .env.local first.");

const GEN_NOW = Date.now();

/** Stable RFC 4122 v4-shaped UUID for a readable seed id. */
export function seedUuid(key) {
  const h = createHash("sha1").update(`nexuspulse:${key}`).digest("hex");
  const variant = ((parseInt(h[16], 16) & 0x3) | 0x8).toString(16);
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-${variant}${h.slice(17, 20)}-${h.slice(20, 32)}`;
}
const sha256 = (s) => createHash("sha256").update(s).digest("hex");

const q = (v) => (v == null ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const id = (key) => (key == null ? "null" : `'${seedUuid(key)}'`);
const ts = (iso) => {
  if (iso == null) return "null";
  const secs = Math.round((GEN_NOW - Date.parse(iso)) / 1000);
  return `(now() - interval '${secs} seconds')`;
};
const period = (iso) => `to_char(${ts(iso)} at time zone 'utc', 'YYYY-MM')`;
const json = (v) => `${q(JSON.stringify(v))}::jsonb`;
const arr = (xs) => (xs.length ? `array[${xs.map(q).join(", ")}]` : "'{}'::text[]");

const out = [];
const emit = (s) => out.push(s);
const insert = (table, rows) => {
  if (!rows.length) return;
  const cols = Object.keys(rows[0]);
  emit(`insert into ${table} (${cols.join(", ")}) values`);
  emit(rows.map((r) => `  (${cols.map((c) => r[c]).join(", ")})`).join(",\n") + ";\n");
};

const profileIds = seed.profiles.map((p) => p.id);
const companyIds = seed.companies.map((c) => c.id);
const nameToProfile = new Map(seed.profiles.map((p) => [p.fullName, p.id]));

emit("-- Generated by scripts/gen-seed.mjs from lib/mock/seed.ts. Do not edit by hand.");
emit("-- Safe to re-run: removes only the seeded users and companies first. One DO block = one statement, all or nothing.\n");
emit("do $seed$ begin\n");

// ---------- reset ----------
// Applications go first: their events and ledger rows are append-only, so letting a
// user delete cascade into them would try to UPDATE (set null) and fail.
const seededUsers = profileIds.map(id).join(", ");
const seededCompanies = companyIds.map(id).join(", ");
emit(
  `delete from public.applications where applicant_id in (${seededUsers}) ` +
    `or job_id in (select id from public.jobs where company_id in (${seededCompanies}));`,
);
emit(`delete from public.token_ledger where applicant_id in (${seededUsers}) or created_by in (${seededUsers});`);
emit(`delete from public.application_events where actor_id in (${seededUsers});`);
emit(`delete from auth.users where id in (${seededUsers});`);
emit(`delete from public.companies where id in (${seededCompanies});`);
emit(`delete from public.blocked_email_domains where reason = 'free_mail';\n`);

// ---------- auth users (trigger creates profiles + applicant_profiles) ----------
insert(
  "auth.users",
  seed.profiles.map((p) => ({
    instance_id: q("00000000-0000-0000-0000-000000000000"),
    id: id(p.id),
    aud: q("authenticated"),
    role: q("authenticated"),
    email: q(p.email),
    encrypted_password: `extensions.crypt(${q(DEMO_PASSWORD)}, extensions.gen_salt('bf'))`,
    email_confirmed_at: "now()",
    raw_app_meta_data: json({ provider: "email", providers: ["email"] }),
    raw_user_meta_data: json({ full_name: p.fullName, role: p.role === "admin" ? null : p.role }),
    created_at: "now()",
    updated_at: "now()",
    confirmation_token: "''",
    recovery_token: "''",
    email_change: "''",
    email_change_token_new: "''",
  })),
);
insert(
  "auth.identities",
  seed.profiles.map((p) => ({
    id: id(`identity:${p.id}`),
    user_id: id(p.id),
    provider_id: q(seedUuid(p.id)),
    provider: q("email"),
    identity_data: json({ sub: seedUuid(p.id), email: p.email, email_verified: true }),
    last_sign_in_at: "now()",
    created_at: "now()",
    updated_at: "now()",
  })),
);
for (const p of seed.profiles) {
  const onboarded = p.role === "admin" || seed.onboardedUserIds.includes(p.id);
  emit(
    `update public.profiles set full_name = ${q(p.fullName)}, avatar_url = ${q(p.avatarUrl)}, role = ${q(p.role)}, ` +
      `onboarded_at = ${onboarded ? "now() - interval '60 days'" : "null"} where id = ${id(p.id)};`,
  );
}
emit("");

// ---------- companies ----------
insert(
  "public.companies",
  seed.companies.map((c) => ({
    id: id(c.id),
    name: q(c.name),
    website: q(c.website),
    logo_url: q(c.logoUrl),
    description: q(c.description),
    verification_status: q(c.verificationStatus),
    verified_at: c.verificationStatus === "verified" ? ts(c.createdAt) : "null",
    rejected_reason: q(c.reviewReason),
    created_at: ts(c.createdAt),
  })),
);
insert(
  "public.company_domains",
  seed.companies.flatMap((c) =>
    c.domains.map((d) => ({
      id: id(`domain:${d}`),
      company_id: id(c.id),
      domain: q(d),
      verification_status: q(c.verificationStatus),
      verification_method: q("admin"),
      verified_at: c.verificationStatus === "verified" ? ts(c.createdAt) : "null",
    })),
  ),
);
insert(
  "public.recruiter_memberships",
  seed.recruiterMemberships.map((m) => ({
    id: id(`membership:${m.recruiterId}`),
    company_id: id(m.companyId),
    profile_id: id(m.recruiterId),
    verification_status: q(m.verificationStatus),
    verified_via: m.verificationStatus === "verified" ? q("email_domain") : "null",
    verified_at: m.verificationStatus === "verified" ? "now() - interval '50 days'" : "null",
    is_company_admin: "true",
    work_email: q(m.workEmail.toLowerCase()),
    work_email_verified_at: m.verificationStatus === "verified" ? "now() - interval '50 days'" : "null",
  })),
);
insert(
  "public.blocked_email_domains",
  seed.blockedEmailDomains.map((d) => ({ domain: q(d), reason: q("free_mail") })),
);

// ---------- jobs ----------
const recruiterFor = new Map(seed.recruiterMemberships.map((m) => [m.companyId, m.recruiterId]));
const jobById = new Map(seed.jobs.map((j) => [j.id, j]));
insert(
  "public.jobs",
  seed.jobs.map((j) => ({
    id: id(j.id),
    company_id: id(j.companyId),
    created_by: id(recruiterFor.get(j.companyId) ?? null),
    title: q(j.title),
    description: q(j.description),
    requirements: q(j.requirements),
    location: q(j.location),
    work_mode: q(j.workMode),
    token_cost: String(j.tokenCost),
    is_technical: String(j.isTechnical),
    status: q(j.status),
    published_at: ts(j.publishedAt),
    created_at: ts(j.createdAt),
    updated_at: ts(j.updatedAt),
  })),
);

// ---------- applicant profiles, resumes, LinkedIn ----------
for (const a of seed.applicantProfiles) {
  emit(
    `insert into public.applicant_profiles (profile_id, headline, target_seniority, location_pref) values ` +
      `(${id(a.id)}, ${q(a.headline)}, ${q(a.targetSeniority)}, ${q(a.locationPref)}) ` +
      `on conflict (profile_id) do update set headline = excluded.headline, target_seniority = excluded.target_seniority, location_pref = excluded.location_pref;`,
  );
}
emit("");
const withResume = seed.applicantProfiles.filter((a) => a.resume);
insert(
  "public.resumes",
  withResume.map((a) => ({
    id: id(a.resume.id),
    applicant_id: id(a.id),
    storage_path: q(`${seedUuid(a.id)}/${seedUuid(a.resume.id)}.pdf`),
    original_filename: q(a.resume.fileName),
    mime_type: q(a.resume.mimeType),
    size_bytes: String(a.resume.sizeBytes),
    text_content: q(a.resume.textContent),
    parse_status: q(a.resume.parseStatus),
  })),
);
const withLinkedin = seed.applicantProfiles.filter((a) => a.linkedin);
insert(
  "public.linkedin_imports",
  withLinkedin.map((a) => ({
    id: id(a.linkedin.id),
    applicant_id: id(a.id),
    source: q("zip"),
    status: q(a.linkedin.status),
    files_present: arr(a.linkedin.filesPresent.map((f) => `${f}.csv`)),
    counts: json(Object.fromEntries(Object.entries(a.linkedin.counts).map(([k, n]) => [k, { parsed: n, skipped: 0 }]))),
    uploaded_at: "now() - interval '30 days'",
    parsed_at: a.linkedin.status === "succeeded" ? "now() - interval '30 days'" : "null",
  })),
);
for (const a of seed.applicantProfiles) {
  emit(
    `update public.applicant_profiles set active_resume_id = ${id(a.resume?.id ?? null)}, ` +
      `active_linkedin_import_id = ${id(a.linkedin?.id ?? null)} where profile_id = ${id(a.id)};`,
  );
}
emit("");
const importFor = new Map(withLinkedin.map((a) => [a.id, a.linkedin.id]));
insert(
  "public.connections",
  seed.connections.map((c) => ({
    id: id(c.id),
    import_id: id(importFor.get(c.ownerId)),
    applicant_id: id(c.ownerId),
    first_name: q(c.firstName),
    last_name: q(c.lastName),
    company_name: q(c.companyName),
    position: q(c.position),
  })),
);

// ---------- fit evaluations, applications, events, repo reviews ----------
const resumeFor = new Map(withResume.map((a) => [a.id, a.resume.id]));
insert(
  "public.fit_evaluations",
  seed.fitEvaluations.map((f) => ({
    id: id(f.id),
    applicant_id: id(f.applicantId),
    job_id: id(f.jobId),
    input_hash: q(sha256(`seed:${f.id}`)),
    status: q(f.status),
    confidence_score: f.confidenceScore == null ? "null" : String(f.confidenceScore),
    explanation: q(f.explanation),
    model: q("seed"),
    prompt_version: q("seed-v1"),
    resume_id: id(resumeFor.get(f.applicantId) ?? null),
    linkedin_import_id: id(importFor.get(f.applicantId) ?? null),
    requirements: json(f.requirements.map((r) => ({ text: r.requirement, importance: "required", status: r.met, evidence: r.evidence }))),
    band: q(f.band),
    job_updated_at: ts(jobById.get(f.jobId).updatedAt),
    started_at: ts(f.createdAt),
    completed_at: f.status === "succeeded" ? ts(f.createdAt) : "null",
    created_at: ts(f.createdAt),
  })),
);
insert(
  "public.applications",
  seed.applications.map((a) => ({
    id: id(a.id),
    job_id: id(a.jobId),
    applicant_id: id(a.applicantId),
    status: q(a.status),
    token_cost: String(a.tokenCost),
    github_repo_url: q(a.githubRepoUrl),
    resume_id: id(resumeFor.get(a.applicantId) ?? null),
    fit_evaluation_id: id(a.fitEvaluationId),
    idempotency_key: id(`idem:${a.id}`),
    request_hash: q(sha256(`seed:${a.id}`)),
    submitted_at: ts(a.submittedAt),
    status_changed_at: ts(a.updatedAt),
    created_at: ts(a.submittedAt),
    updated_at: ts(a.updatedAt),
  })),
);
insert(
  "public.application_events",
  seed.applications.flatMap((a) =>
    a.events.map((e, i) => ({
      id: id(`event:${a.id}:${i}`),
      application_id: id(a.id),
      actor_id: e.actorName ? id(nameToProfile.get(e.actorName) ?? null) : e.fromStatus == null ? id(a.applicantId) : "null",
      from_status: q(e.fromStatus),
      to_status: q(e.toStatus),
      created_at: ts(e.at),
    })),
  ),
);
insert(
  "public.repo_evaluations",
  seed.repoEvaluations.map((r) => ({
    id: id(r.id),
    application_id: id(r.applicationId),
    repo_url: q(r.repoUrl.toLowerCase()),
    commit_sha: q(r.commitSha),
    status: q(r.status),
    data_architecture_score: r.scores ? String(r.scores.dataArchitecture) : "null",
    performance_score: r.scores ? String(r.scores.performance) : "null",
    deployment_score: r.scores ? String(r.scores.deployment) : "null",
    code_quality_score: r.scores ? String(r.scores.codeQuality) : "null",
    team_topology_score: r.scores ? String(r.scores.teamTopology) : "null",
    rationale: r.scores ? json(Object.fromEntries(Object.entries(r.rationale).map(([k, v]) => [k, { summary: v }]))) : "null",
    repo_meta: json({ full_name: r.repoFullName, is_fork: r.flags.includes("fork") }),
    flags: json({ likely_template_or_fork: r.flags.includes("fork") }),
    failure_code: q(r.failureCode),
    error: r.failureCode ? q(r.failureCode) : "null",
    model: r.scores ? q("seed") : "null",
    prompt_version: q("seed-v1"),
    completed_at: r.status === "succeeded" || r.status === "failed" ? "now() - interval '1 hour'" : "null",
  })),
);

// ---------- token ledger: one spend per application ----------
insert(
  "public.token_ledger",
  seed.applications.map((a) => ({
    id: id(`spend:${a.id}`),
    applicant_id: id(a.applicantId),
    period: period(a.submittedAt),
    kind: q("application_spend"),
    amount: String(-a.tokenCost),
    application_id: id(a.id),
    created_at: ts(a.submittedAt),
  })),
);

emit("end $seed$;");

writeFileSync(new URL("supabase/seed.sql", root), out.join("\n") + "\n");
console.log(`Wrote supabase/seed.sql (${out.length} statements/blocks).`);
